# Generated by Django 5.2.7 on 2025-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
    ]
